import { readFileSync, existsSync } from "node:fs";
import { gunzipSync } from "node:zlib";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import type { CantonCode, TariffCode } from "@rappen/shared";
import { CANTONS } from "@rappen/shared";
import type { CantonTariffData, CompactTariffSeries } from "../types.js";
import { buildEstvCode } from "../types.js";

/**
 * Loads ESTV-derived withholding tax tariffs from gzipped JSON files at runtime.
 *
 * Data files are stored OUTSIDE the src/ tree (in packages/swiss-data/data/qst-2026/)
 * so they are NOT bundled by webpack — instead they are read by Node at runtime
 * and the result is cached in memory after first access.
 *
 * Source: ESTV official 2026 tariff publication (Lohnformat).
 * Generated by: scripts/parse-estv-tariffs.ts
 */

// ════════════════════════════════════════════════════════════════
// Path resolution
// ════════════════════════════════════════════════════════════════

let cachedDataDir: string | null = null;

function getDataDir(): string {
	if (cachedDataDir) return cachedDataDir;

	// Strategy 1: derive from import.meta.url (works in ESM Node and Vitest)
	try {
		const here = dirname(fileURLToPath(import.meta.url));
		// here = .../packages/swiss-data/src/withholding-tax/tariffs
		const candidate = join(here, "..", "..", "..", "data", "qst-2026");
		if (existsSync(candidate)) {
			cachedDataDir = candidate;
			return candidate;
		}
	} catch {
		// import.meta.url not available — fall through
	}

	// Strategy 2: derive from process.cwd() (works in Next.js production
	// when called from a Server Action)
	const cwd = process.cwd();
	const candidates = [
		join(cwd, "packages", "swiss-data", "data", "qst-2026"),
		join(cwd, "..", "..", "packages", "swiss-data", "data", "qst-2026"),
		join(cwd, "..", "packages", "swiss-data", "data", "qst-2026"),
	];
	for (const c of candidates) {
		if (existsSync(c)) {
			cachedDataDir = c;
			return c;
		}
	}

	throw new Error(
		`QST tariff data directory not found. Tried: ${candidates.join(", ")}. ` +
			"Run `pnpm tsx scripts/parse-estv-tariffs.ts` to generate it.",
	);
}

// ════════════════════════════════════════════════════════════════
// In-memory cache
// ════════════════════════════════════════════════════════════════

const cache = new Map<string, CantonTariffData>();

function loadCanton(canton: CantonCode): CantonTariffData {
	const cached = cache.get(canton);
	if (cached) return cached;

	const path = join(getDataDir(), `${canton}.json.gz`);
	if (!existsSync(path)) {
		throw new Error(`No QST tariff file for canton ${canton}: ${path}`);
	}

	const compressed = readFileSync(path);
	const json = gunzipSync(compressed).toString("utf-8");
	const data = JSON.parse(json) as CantonTariffData;
	cache.set(canton, data);
	return data;
}

// ════════════════════════════════════════════════════════════════
// Public API
// ════════════════════════════════════════════════════════════════

/**
 * All cantons for which official ESTV 2026 tariffs are loaded.
 * Currently: all 26 Swiss cantons.
 */
export const SUPPORTED_QST_CANTONS: ReadonlyArray<CantonCode> = CANTONS;

/**
 * Returns true if withholding tax tariffs are loaded for this canton.
 */
export function isQstCantonSupported(canton: CantonCode): boolean {
	return SUPPORTED_QST_CANTONS.includes(canton);
}

/**
 * Look up a single tariff series by canton, group, child count, and church.
 *
 * Handles canton-specific exceptions per ESTV spec section 1.2 / Abacus doc:
 * - GE/NE/VD/VS/TI: only "ohne Kirchensteuer" (church=false). Y is mapped to N.
 * - JU: only "mit Kirchensteuer" (church=true). N is mapped to Y.
 *
 * Returns null if no matching tariff is found.
 */
export function getTariff(
	canton: CantonCode,
	group: TariffCode,
	children: number,
	church: boolean,
	year: number = 2026,
): CompactTariffSeries | null {
	if (year !== 2026) {
		throw new Error(`Only 2026 tariffs are currently supported (requested: ${year})`);
	}

	const data = loadCanton(canton);

	// Apply canton-specific church-tax rules
	const NO_CHURCH_CANTONS = new Set<CantonCode>(["GE", "NE", "VD", "VS", "TI"]);
	const ONLY_CHURCH_CANTONS = new Set<CantonCode>(["JU"]);

	let effectiveChurch = church;
	if (NO_CHURCH_CANTONS.has(canton)) effectiveChurch = false;
	if (ONLY_CHURCH_CANTONS.has(canton)) effectiveChurch = true;

	// Tariff code H requires at least 1 child
	if (group === "H" && children < 1) {
		return null;
	}

	const code = buildEstvCode(group, children, effectiveChurch);
	return data.tariffs[code] ?? null;
}

/**
 * Get the canton's median monthly salary (used for tariff C calculation).
 */
export function getMedianSalary(canton: CantonCode): number | null {
	return loadCanton(canton).median_salary;
}

/**
 * Get all available tariff codes for a canton (debug/validation).
 */
export function getAvailableTariffsForCanton(canton: CantonCode): string[] {
	return Object.keys(loadCanton(canton).tariffs).sort();
}

/**
 * Get the data file metadata (created_at, source) for a canton.
 */
export function getCantonDataMeta(canton: CantonCode): {
	created_at: string;
	source: string;
	median_salary: number | null;
	tariff_count: number;
} {
	const data = loadCanton(canton);
	return {
		created_at: data.created_at,
		source: data.source,
		median_salary: data.median_salary,
		tariff_count: Object.keys(data.tariffs).length,
	};
}

/**
 * Backwards-compat alias used by older tests.
 */
export function getAvailableTariffs(): string[] {
	const all: string[] = [];
	for (const canton of CANTONS) {
		try {
			for (const code of getAvailableTariffsForCanton(canton)) {
				all.push(`${canton}_${code}`);
			}
		} catch {
			// Canton not yet available
		}
	}
	return all;
}
