import { readFileSync, existsSync, readdirSync } from "node:fs";
import { gunzipSync } from "node:zlib";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import type { CantonCode, TariffCode } from "@rappen/shared";
import { CANTONS } from "@rappen/shared";
import type { CantonTariffData, CompactTariffSeries } from "../types.js";
import { buildEstvCode } from "../types.js";

/**
 * Loads ESTV-derived withholding tax tariffs from gzipped JSON files at runtime.
 *
 * Data files are stored OUTSIDE the src/ tree (in packages/swiss-data/data/qst-{YEAR}/)
 * so they are NOT bundled by webpack — instead they are read by Node at runtime
 * and cached in memory after first access.
 *
 * Year discovery:
 * - On first access, the loader scans packages/swiss-data/data/qst-* for available years
 * - The "current" year is the highest available year ≤ today's year
 * - Older years remain accessible if their data is present
 *
 * Source: ESTV official tariff publications (Lohnformat).
 * Updated by: scripts/update-qst-tariffs.ts (annual cron)
 * Generated by: scripts/parse-estv-tariffs.ts
 */

// ════════════════════════════════════════════════════════════════
// Path resolution & year discovery
// ════════════════════════════════════════════════════════════════

let cachedDataRoot: string | null = null;

/**
 * Locate the swiss-data/data root directory. This is the parent of all
 * year-specific tariff folders (e.g. qst-2026, qst-2027).
 */
function getDataRoot(): string {
	if (cachedDataRoot) return cachedDataRoot;

	// Strategy 1: derive from import.meta.url (works in ESM Node and Vitest)
	try {
		const here = dirname(fileURLToPath(import.meta.url));
		// here = .../packages/swiss-data/src/withholding-tax/tariffs
		const candidate = join(here, "..", "..", "..", "data");
		if (existsSync(candidate)) {
			cachedDataRoot = candidate;
			return candidate;
		}
	} catch {
		// import.meta.url not available — fall through
	}

	// Strategy 2: derive from process.cwd() (works in Next.js production
	// when called from a Server Action)
	const cwd = process.cwd();
	const candidates = [
		join(cwd, "packages", "swiss-data", "data"),
		join(cwd, "..", "..", "packages", "swiss-data", "data"),
		join(cwd, "..", "packages", "swiss-data", "data"),
	];
	for (const c of candidates) {
		if (existsSync(c)) {
			cachedDataRoot = c;
			return c;
		}
	}

	throw new Error(
		`QST tariff data root not found. Tried: ${candidates.join(", ")}. ` +
			"Run `pnpm tsx scripts/update-qst-tariffs.ts` to generate it.",
	);
}

let cachedAvailableYears: number[] | null = null;

/**
 * List all years for which tariff data is currently bundled.
 * Returns sorted ascending. Empty if no data is available.
 */
export function listAvailableQstYears(): number[] {
	if (cachedAvailableYears) return cachedAvailableYears;

	try {
		const root = getDataRoot();
		const entries = readdirSync(root, { withFileTypes: true });
		const years = entries
			.filter((e) => e.isDirectory() && /^qst-\d{4}$/.test(e.name))
			.map((e) => parseInt(e.name.substring(4), 10))
			.filter((y) => !Number.isNaN(y))
			.sort((a, b) => a - b);
		cachedAvailableYears = years;
		return years;
	} catch {
		cachedAvailableYears = [];
		return [];
	}
}

/**
 * The latest year for which tariff data is available.
 * Defaults to the current calendar year if data is present, otherwise
 * falls back to the most recent year with data.
 */
export function getLatestQstYear(): number {
	const years = listAvailableQstYears();
	if (years.length === 0) {
		throw new Error("No QST tariff data available. Run scripts/update-qst-tariffs.ts");
	}
	return years[years.length - 1];
}

/**
 * The "current" year for tariff calculations: the latest year ≤ today's year.
 * If only future years are bundled, falls back to the latest available.
 */
export function getCurrentQstYear(): number {
	const years = listAvailableQstYears();
	if (years.length === 0) {
		throw new Error("No QST tariff data available. Run scripts/update-qst-tariffs.ts");
	}
	const today = new Date().getFullYear();
	const eligible = years.filter((y) => y <= today);
	return eligible.length > 0 ? eligible[eligible.length - 1] : years[years.length - 1];
}

function getYearDataDir(year: number): string {
	return join(getDataRoot(), `qst-${year}`);
}

// ════════════════════════════════════════════════════════════════
// In-memory cache (per year × canton)
// ════════════════════════════════════════════════════════════════

const cache = new Map<string, CantonTariffData>();

function loadCanton(canton: CantonCode, year: number): CantonTariffData {
	const cacheKey = `${year}:${canton}`;
	const cached = cache.get(cacheKey);
	if (cached) return cached;

	const path = join(getYearDataDir(year), `${canton}.json.gz`);
	if (!existsSync(path)) {
		throw new Error(`No QST tariff file for canton ${canton} in year ${year}: ${path}`);
	}

	const compressed = readFileSync(path);
	const json = gunzipSync(compressed).toString("utf-8");
	const data = JSON.parse(json) as CantonTariffData;
	cache.set(cacheKey, data);
	return data;
}

// ════════════════════════════════════════════════════════════════
// Public API
// ════════════════════════════════════════════════════════════════

/**
 * All cantons for which official ESTV tariffs are loaded.
 * Currently: all 26 Swiss cantons.
 */
export const SUPPORTED_QST_CANTONS: ReadonlyArray<CantonCode> = CANTONS;

/**
 * Returns true if withholding tax tariffs are loaded for this canton.
 */
export function isQstCantonSupported(canton: CantonCode): boolean {
	return SUPPORTED_QST_CANTONS.includes(canton);
}

/**
 * Look up a single tariff series by canton, group, child count, and church.
 *
 * Handles canton-specific exceptions per ESTV spec section 1.2 / Abacus doc:
 * - GE/NE/VD/VS/TI: only "ohne Kirchensteuer" (church=false). Y is mapped to N.
 * - JU: only "mit Kirchensteuer" (church=true). N is mapped to Y.
 *
 * Returns null if no matching tariff is found.
 *
 * @param year - Tax year. Defaults to the latest available year ≤ today.
 */
export function getTariff(
	canton: CantonCode,
	group: TariffCode,
	children: number,
	church: boolean,
	year?: number,
): CompactTariffSeries | null {
	const targetYear = year ?? getCurrentQstYear();
	const available = listAvailableQstYears();
	if (!available.includes(targetYear)) {
		throw new Error(
			`Year ${targetYear} not available. Available years: ${available.join(", ") || "(none)"}.`,
		);
	}

	const data = loadCanton(canton, targetYear);

	// Apply canton-specific church-tax rules
	const NO_CHURCH_CANTONS = new Set<CantonCode>(["GE", "NE", "VD", "VS", "TI"]);
	const ONLY_CHURCH_CANTONS = new Set<CantonCode>(["JU"]);

	let effectiveChurch = church;
	if (NO_CHURCH_CANTONS.has(canton)) effectiveChurch = false;
	if (ONLY_CHURCH_CANTONS.has(canton)) effectiveChurch = true;

	// Tariff code H requires at least 1 child
	if (group === "H" && children < 1) {
		return null;
	}

	const code = buildEstvCode(group, children, effectiveChurch);
	return data.tariffs[code] ?? null;
}

/**
 * Get the canton's median monthly salary (used for tariff C calculation).
 */
export function getMedianSalary(canton: CantonCode, year?: number): number | null {
	return loadCanton(canton, year ?? getCurrentQstYear()).median_salary;
}

/**
 * Get all available tariff codes for a canton (debug/validation).
 */
export function getAvailableTariffsForCanton(canton: CantonCode, year?: number): string[] {
	return Object.keys(loadCanton(canton, year ?? getCurrentQstYear()).tariffs).sort();
}

/**
 * Get the data file metadata (created_at, source) for a canton.
 */
export function getCantonDataMeta(
	canton: CantonCode,
	year?: number,
): {
	year: number;
	created_at: string;
	source: string;
	median_salary: number | null;
	tariff_count: number;
} {
	const targetYear = year ?? getCurrentQstYear();
	const data = loadCanton(canton, targetYear);
	return {
		year: targetYear,
		created_at: data.created_at,
		source: data.source,
		median_salary: data.median_salary,
		tariff_count: Object.keys(data.tariffs).length,
	};
}

/**
 * Backwards-compat alias used by older tests.
 */
export function getAvailableTariffs(): string[] {
	const all: string[] = [];
	for (const year of listAvailableQstYears()) {
		for (const canton of CANTONS) {
			try {
				for (const code of getAvailableTariffsForCanton(canton, year)) {
					all.push(`${year}_${canton}_${code}`);
				}
			} catch {
				// Canton not yet available
			}
		}
	}
	return all;
}

/**
 * Reset the in-memory cache. Used by tests.
 */
export function _resetQstCache() {
	cache.clear();
	cachedDataRoot = null;
	cachedAvailableYears = null;
}
